source 'http://rubygems.org'

gem 'bson_ext'
gem 'cancan', '~> 1.5'
gem 'curb', '~> 0.7'
gem 'database_cleaner', '~> 0.6'
gem 'devise', '~> 1.1'
gem 'factory_girl', '~> 1.3'
gem 'haml', '~> 3.0'
gem 'kronos', '~> 0.3'
gem 'mongoid', '~> 2.0.0.rc.7'
gem 'mongoid_slug', '~> 0.6', :require => 'mongoid/slug'
gem 'nokogiri', '~> 1.4'
gem 'rails', '~> 3.0'
gem 'rdiscount', '~> 1.6'
gem 'rails3-jquery-autocomplete', '~> 0.6'
gem 'resque', '~> 1.10'
gem 'resque-scheduler', '~> 1.9'
gem 'unicorn', '~> 3.3'

group :test, :development do
  gem 'autotest', '~> 4.4'
  gem 'capistrano', '~> 2.5'
  gem 'metric_fu', '~> 2.0'
  gem 'rspec-rails', '~> 2.4'
end
